### ISSUE TITLE
Bad interaction with `crosstalk`

### ISSUE THREAD

**Issue by dmurdoch** [rte-antares-rpackage/manipulateWidget#46]
I'm not sure if this is a `crosstalk` issue or a `manipulateWidget` issue, but if I write e.g.

    library(crosstalk)
    library(manipulateWidget)
    sd <- SharedData$new(mtcars)
    combineWidgets(filter_slider("mpg", "Miles per gallon", sd, "mpg"))

the slider doesn't appear to get initialized properly, I just get a simple label and input box.  (The real case has several widgets as well as the `filter_slider`, of course.)

This is using `crosstalk 1.0.1` and `manipulateWidget 0.8.0`, both current on Github.

I'll post a link to this issue on the `crosstalk` repos.

**Comment by bthieurmel** [comment]
Thanks. Merge your PR in ``next_release`` branch.
