### ISSUE TITLE
combineWidgets loses class of widgets

### ISSUE THREAD

**Issue by dmurdoch** [rte-antares-rpackage/manipulateWidget#49]
htmlwidgets creates a class for the div holding a widget that contains the name of the widget, and some other stuff.  combineWidgets just uses class `cw-widget`, ignoring the original class.

This causes trouble for `rgl`, because it provides some style info in a CSS file that depends on the class attribute for the div.  

I have a patch on dmurdoch/manipulateWidget in the `keepclass` branch, but it also includes the previous patch.  I don't know how to submit a PR that only includes the new stuff.

**Comment by bthieurmel** [comment]
Thanks. Merge your PR in ``next_release``.
