### ISSUE TITLE
Combine HTML Widgets with DataTables

### ISSUE THREAD

**Issue by mansaluke** [rte-antares-rpackage/manipulateWidget#61]
Hi all,

Firstly thanks to the developers for this package which is very useful. The issue I have found is that when using the package it does not seem to be possible to use DT datatables in the combine widgets command.

Is it possible to integrate the data table into a single view alongside other widgets using the combine widgets command? If so, how can this be done? And, if not, why not?

This is what i've tried but the data table does not show up:
```
library(manipulateWidget)
library(plotly)
library(DT)

if (require(plotly)) {
  data(iris)
  
  combineWidgets(title = "The iris data set: sepals", ncol = 2, colsize = c(2,1),
                 plot_ly(iris, x = ~Sepal.Length, y = ~Sepal.Width, type = "scatter",
                         mode = "markers", color = ~Species),
                 datatable(iris)
                 )
}
```

Thanks in advance. :)

**Comment by FrancoisGuillem** [comment]
Hello,

This is a strange issue, because if I use your code in function manipulateWidget, the table appears correctly:

```r
manipulateWidget({
combineWidgets(title = "The iris data set: sepals", ncol = 2, colsize = c(2,1),
               plot_ly(iris, x = ~Sepal.Length, y = ~Sepal.Width, type = "scatter",
                       mode = "markers", color = ~Species),
               datatable(iris))
}, select = mwSelect(1:3))
```
![image](https://user-images.githubusercontent.com/3432606/49159196-3813e400-f324-11e8-8225-fa32f613abe3.png)

**Comment by mansaluke** [comment]
Thanks that seems to have solved it. Although its a bit strange that the same code worked with other packages.
